name       : xvidcore
version    : 1.3.5
release    : 2
source     :
    - http://downloads.xvid.org/downloads/xvidcore-1.3.5.tar.gz : 165ba6a2a447a8375f7b06db5a3c91810181f2898166e7c8137401d7fc894cf0
license    : GPL-2.0
component  : multimedia.library
summary    : Xvid MPEG-4 video codec
description: |
    Xvid MPEG-4 video codec
builddeps  :
    - nasm
setup      : |
    cd build/generic
    %configure --disable-static
build      : |
    cd build/generic
    %make
install    : |
    cd build/generic
    %make_install
    rm $installdir/%libdir%/libxvidcore.a
