name       : xvidcore
version    : 1.3.4
release    : 1
source     :
    - http://downloads.xvid.org/downloads/xvidcore-1.3.4.tar.gz : 4e9fd62728885855bc5007fe1be58df42e5e274497591fec37249e1052ae316f
license    : GPL-2.0 # CHECK ME
summary    : Xvid MPEG-4 video codec 
description: |
        Xvid MPEG-4 video codec
builddeps  :
setup      : |
    build/generic/%configure
build      : |
        cd build/generic && %make 
install    : |
        cd build/generic && %make_install 
